package(default_visibility = ["//obr:__subpackages__"])

# keep-sorted start block=yes prefix_order=filegroup newline_separated=yes
filegroup(
    name = "input_wav_files",
    srcs = glob(["*.wav"]),
)

filegroup(
    name = "textprotos",
    srcs = glob(["*.textproto"]),
)

# keep-sorted end
